unit WR_EditCar_Lang;
interface

const
kmhID: array [1..9] of string = (
'0-220 Km/h','0-240 Km/h','0-260 Km/h','0-280 Km/h',
'0-300 Km/h','0-330 Km/h','0-360 Km/h','0-480 Km/h','none');

mphID: array [1..7] of string = (
'0-140 Mph','0-160 Mph','0-180 Mph','0-200 Mph',
'0-220 Mph','0-300 Mph','none');

WRkmhID: array [1..9] of string = (
'0-140 Km/h','0-160 Km/h','0-180 Km/h','0-220 Km/h',
'0-240 Km/h','0-280 Km/h','0-320 Km/h','0-360 Km/h','0-440 Km/h');

WRmphID: array [1..7] of string = (
'0-140 Mph','0-160 Mph','0-180 Mph','0-220 Mph',
'0-240 Mph','0-280 Mph','0-100 Mph');

WRtachoID: array [1..7] of string = (
'0-6.000 rpm','0-7.000 rpm','0-8.000 rpm','0-10.000 rpm',
'0-12.000 rpm','0-13.000 rpm','0-9.000 rpm');

dataType: array [1..2,0..329] of integer =(
(3 //int,real,str                                                                                                                                                    ///////
,1,3,3,1,2,2,2,2,1,1,1,1,1,1,2,2,2,2,2,2,1,3,1,3,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,1,2,2,1,1,1,1,1
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1),
(3
,1,1,3,1,1,1,1,1,2,1,1,1,1,1,3,1,1,2,2,2,2,1,2,2,2,2,1,2,1,2,1,1,1,2,2,1,2,2,1,1,1,1,2,2,1,3,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,3,1,1,3,3,1,3,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,3,3,3
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
,1,1));

dataText: array [1..2,0..329,1..5] of string =(
(('Kommentar','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FzeugData','Index','Klassenbezeichnung')
,('Index','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Index')
,('EngineName','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','BasisModellName')
,('EngineNameClose','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','BasisModellalternative')
,('UserFlagCabrio','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','BasisModellName')
,('Pos-Vorderreifen-Spur','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Pos-Vorderreifen-Spur')
,('Pos-Hinterreifen-Spur','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Pos-Hinterreifen-Spur')
,('Pos-Vorderreifen-Z-Achse','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Pos-Vorderreifen-Z-Achse')
,('Pos-Hinterrreifen-Z-Achse','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Pos-Hinterrreifen-Z-Achse')
,('BRLichtrMatid1','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','BRLichtrMatid1')
,('BRLichtrMatid2','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','BRLichtrMatid2')
,('BRLichtrMatid3','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','BRLichtrMatid3')
,('SWLichtMatid1','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','SWLichtMatid1')
,('SWLichtMatid2','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','SWLichtMatid2')
,('SWLichtMatid3','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','SWLichtMatid3')
,('VerfolgerKameraHoehe','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','VerfolgerKameraHoehe')
,('VerfolgerKameraEntfernung','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','VerfolgerKameraEntfernung')
,('InnenKameraHoehe','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','InnenKameraHoehe')
,('InnenKameraEntfernung','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','InnenKameraEntfernung')
,('CockpitKameraHoehe','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','CockpitKameraHoehe')
,('CockpitKameraEntfernung','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','CockpitKameraEntfernung')
,('LastSelectCar','','','','')
,('ClassName','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','TEXTID')
,('Order','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Klassenreihenfolge')
,('Ref3DCarsOrder','','','','')
,('UserColorID','','','','')
,('CockpitKameraXpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','CockpitKameraXpos')
,('FlagCabrio','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','AutoIstCabrio')
,('CAB_BRLichtrMatid1','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','CAB_BRLichtrMatid1')
,('CAB_BRLichtrMatid2','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','CAB_BRLichtrMatid2')
,('CAB_BRLichtrMatid3','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','CAB_BRLichtrMatid3')
,('SplitUser1LastSelectCar','','','','')
,('SplitUser2LastSelectCar','','','','')
,('SplitUser3LastSelectCar','','','','')
,('SplitUser4LastSelectCar','','','','')
,('SplitUser1ColorID','','','','')
,('SplitUser2ColorID','','','','')
,('SplitUser3ColorID','','','','')
,('SplitUser4ColorID','','','','')
,('SplitUser1FlagCabrio','','','','')
,('SplitUser2FlagCabrio','','','','')
,('SplitUser3FlagCabrio','','','','')
,('SplitUser4FlagCabrio','','','','')
,('KopfXpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','KopfXpos')
,('KopfYpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','KopfYpos')
,('KopfZpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','KopfZpos')
,('LenkXpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','LenkXpos')
,('LenkYpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','LenkYpos')
,('LenkZpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','LenkZpos')
,('LenkWpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','LenkWpos')
,('KopfXpos2','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','KopfXpos2')
,('KopfYpos2','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','KopfYpos2')
,('KopfZpos2','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','KopfZpos2')
,('Tacho1Modus','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Modus')
,('Tacho1Xpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Xpos')
,('Tacho1Ypos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Ypos')
,('Tacho1Zpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Zpos')
,('Tacho1Xvec','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Xvec')
,('Tacho1Yvec','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Yvec')
,('Tacho1Zvec','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Zvec')
,('Tacho1Scale','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Scale')
,('Tacho1Offs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Offs')
,('Tacho1Size','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho1Size')
,('Tacho2Modus','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Modus')
,('Tacho2Xpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Xpos')
,('Tacho2Ypos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Ypos')
,('Tacho2Zpos','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Zpos')
,('Tacho2Xvec','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Xvec')
,('Tacho2Yvec','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Yvec')
,('Tacho2Zvec','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Zvec')
,('Tacho2Scale','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Scale')
,('Tacho2Offs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Offs')
,('Tacho2Size','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Tacho2Size')
,('Order26','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','Order26')
,('MhaubenKameraHoehe','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','MhaubenKameraHoehe')
,('MhaubenKameraEntfernung','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','_3D_FZeugData','Index','MhaubenKameraEntfernung')
,('UserVinyl','','','','')
,('NumVinyls','','','','')
,('UserRim','','','','')
,('Marker','','','','')
,('ColorIndex','D:\NxNlocal\World Racing 2\_Database\WR2-Autos.mdb','_3D_FZeugData','Index','ColorIndex')
,('DienstwagenFlag','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash')
,('WR2NoDemo','.\','Encrypted','Index','MDHash'),('WR2NoDemo','.\','Encrypted','Index','MDHash'))

,//2nd
(('Kommentar','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Bezeichnung')
,('Index','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Index')
,('_3DCarID','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','D3Modelldaten')
,('CarName','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','TextID')
,('Score','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Leistungsindex')
,('FlagRelease','','','','')
,('UserMark','','','','')
//,('FlagMissionCar','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','NurMissionAuto')
,('CarClassID','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','NurMissionAuto')
,('NoDrives','','','','')
,('kmDistance','','','','')
,('kmhTopSpeed','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','AutoModelle','Index','Hoechstgeschwindigkeitkmh')
,('MotorID','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Motordaten')
,('GetriebeTypSchaltungID','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','GetriebeTypSchaltung')
,('StandardreifenID','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Standardreifen')
,('StandardreifenhintenID','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Standardreifenhinten')
,('TypLinks','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','TypLinks')
,('D?mpferh?rte','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','D?mpferh?rte')
,('Federh?rte','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Federh?rte')
,('AusfedernMaximal','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','AusfedernMaximal')
,('EinfedernMaximal','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','EinfedernMaximal')
,('Grip','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Grip')
,('GripHintenzuVorneinProzent','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','GripHintenzuVorneinProzent')
,('Drehimpuls','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Drehimpuls')
,('Reifenschlupfvorne','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Reifenschlupfvorne')
,('Reifenschlupfhinten','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Reifenschlupfhinten')
,('R?ckstellkr?fte_der_Reifen','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','R?ckstellkr?fte_der_Reifen')
,('Stabilisatoren','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Stabilisatoren')
,('GewichtvorneinProzent','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','GewichtvorneinProzent')
,('Schwerpunkt?berRRadiusinDM','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Schwerpunkt?berRRadiusinDM')
,('Drehmomentfalkor','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Drehmomentfalkor')
,('KraftstoffverbrauchimMittel','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','KraftstoffverbrauchimMittel')
,('Tankinhalt','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Tankinhalt')
,('Leergewicht_KG','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Leergewicht_KG')
,('Abgeregelt','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Abgeregelt')
,('?bersetzungLenkung','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','?bersetzungLenkung')
,('Lenkradumdrehungen','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Lenkradumdrehungen')
,('Antrieb','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Antrieb')
,('Gesamt?bersetzungSchaltung','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Gesamt?bersetzungSchaltung')
,('LuftwiderstandEngine','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','LuftwiderstandEngine')
,('SchlupfredVorne','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','SchlupfredVorne')
,('SchlupfredHinten','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','SchlupfredHinten')
,('Sperrdiff','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','Sperrdiff')
,('RaceClass','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','FahrzeugklasseGesamt')
,('ReifenYPOS','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Automodelle','Index','ReifenYPOS')
,('Beschleunigung0100','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','AutoModelle','Index','Beschleunigung0100')
,('mphTopSpeed','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','AutoModelle','Index','TopSpeed in MPH')
,('TypRechts','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','AutoModelle','Index','TypRechts')
,('TachoKmh','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','AutoModelle','Index','TachoKmh')
,('TachoMPH','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','AutoModelle','Index','TachoMPH')
,('MAXDREHZAHL','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','MAXDREHZAHL')
,('DRM0Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM0Revs')
,('DRM500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM500Revs')
,('DRM1000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM1000Revs')
,('DRM1500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM1500Revs')
,('DRM2000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM2000Revs')
,('DRM2500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM2500Revs')
,('DRM3000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM3000Revs')
,('DRM3500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM3500Revs')
,('DRM4000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4000Revs')
,('DRM4500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM5000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM5500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM6000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM6500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM7000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM7500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM8000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM8500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM9000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM9500Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('DRM10000Revs','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','DRM4500Revs')
,('NMStep','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','NMStep')
,('Motorbremse','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','Motorbremse')
,('Schwungmasse','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','Schwungmasse')
,('SampleRate','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','SampleRate')
,('Motorsample','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','Motorsample')
,('LeistungKW','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','LeistungKW')
,('LeistungPS','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','LeistungPS')
,('LeistungbeiUmin','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','LeistungbeiUmin')
,('Hubraum','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','Hubraum')
,('max_Drehmoment','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','max_Drehmoment')
,('max_Drehmoment_beiUmin','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','max_Drehmoment_beiUmin')
,('Lastgeraeusch','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','Lastgeraeusch')
,('Lautstaerke','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Motoren','Index','Lautstaerke')
,('AnzahlGaenge','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','AnzahlGaenge')
,('Gang1','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','Gang1')
,('Gang2','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','Gang2')
,('gang3','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','gang3')
,('Gang4','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','Gang4')
,('Gang5','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','Gang5')
,('Gang6','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','Gang6')
,('Gang7','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','Gang7')
,('RWGang','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','RWGang')
,('FrontReifenRadius','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','ReifenFelgen','Index','reifenradius')
,('FrontReifenBreite','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','ReifenFelgen','Index','ENGINE_ReifenBreite')
,('FrontFelgenHoehe','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','ReifenFelgen','Index','ENGINE_FELGENHOEHE')
,('BackReifenRadius','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','ReifenFelgen','Index','reifenradius')
,('BackReifenBreite','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','ReifenFelgen','Index','ENGINE_ReifenBreite')
,('BackFelgenHoehe','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','ReifenFelgen','Index','ENGINE_FELGENHOEHE')
,('Drehzahlmesser','','','','')
,('Sauggeraeusch','','','','')
,('Lastgeraeusch','','','','')
,('AuspuffID','','','','')
,('MotorIDSound','','','','')
,('HerstellerName','','','','')
,('HerstellerLogo','','','','')
,('Anbauten','','','','')
,('ClassTextID','','','','')
,('BitmapFilename','','','','')
,('BitmapPosX','','','','')
,('BitmapPosY','','','','')
,('Gang8','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','Gang8')
,('Gang9','D:\NxNlocal\MBC Entwicklung\FrontEnd\_Database\MBWR-Autos.mdb','Getriebe','INDEX','Gang9')//,('mocod','','','','')
//,('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')
,('','','','',''),('','','','',''),('','','','',''),('','','','',''),('','','','','')

,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash'),('Hash','.\','MD','Index','MDHash')
,('Hash','.\','MD','Index','MDHash')));
         

implementation

end.


